import type { AgentRequest, AgentStep, ForgeState } from "../types";
import { listFiles, readWorkspaceFile, writeWorkspaceFile } from "../core/filesystem";
import { runCommand } from "../terminal/exec";
import { assertPermission } from "../core/permissions";

export async function runAgent(state: ForgeState, req: AgentRequest): Promise<AgentStep[]> {
  const steps: AgentStep[] = [];
  const maxSteps = Math.max(1, Math.min(req.maxSteps ?? 5, 20));

  steps.push({ step: 1, action: "planner", result: `Task planned: ${req.task}` });

  if (maxSteps >= 2) {
    assertPermission(state, "read");
    const files = await listFiles(state.projectRoot, 30);
    steps.push({ step: 2, action: "scan_workspace", result: `Found ${files.length} files` });
  }

  if (maxSteps >= 3 && /read\s+/i.test(req.task)) {
    const maybe = req.task.match(/read\s+([^\s]+)/i)?.[1];
    if (maybe) {
      const content = await readWorkspaceFile(state.projectRoot, maybe);
      steps.push({ step: 3, action: "read_file", result: content.slice(0, 300) });
    }
  }

  if (maxSteps >= 4 && /write\s+/i.test(req.task)) {
    assertPermission(state, "write");
    const maybe = req.task.match(/write\s+([^\s]+)/i)?.[1];
    if (maybe) {
      await writeWorkspaceFile(state.projectRoot, maybe, "# Generated by Cognautic Forge CLI\n");
      steps.push({ step: 4, action: "write_file", result: `Wrote ${maybe}` });
    }
  }

  if (maxSteps >= 5 && /run\s+/i.test(req.task)) {
    assertPermission(state, "command");
    const cmd = req.task.match(/run\s+(.+)/i)?.[1] ?? "echo no command";
    const res = await runCommand(cmd, state.projectRoot);
    steps.push({ step: 5, action: "run_command", result: `exit=${res.code}` });
  }

  return steps;
}
